### ISSUE TITLE
pwmerge group selection broken

### ISSUE THREAD

**Issue by trickkiste** [ltsp/ltsp#139]
I ran a test on pwmerge locally, to see what it is actually doing and ran into this problem:

```
elias@maas:~/tmp$ sudo pwmerge --sur="a^" --sgr=".*" --dur=".*" --dgr=".*" -l etc.server/ etc.boot/ etc.target/
Marked destination users for regexes '.*', '.*':
 root daemon bin sys sync (.... and all other groups apparently)
Removed destination users:

Removed destination groups:

Marked source users for regexes 'a^', '.*':
Traceback (most recent call last):
  File "/usr/local/bin/pwmerge", line 440, in <module>
    main(sys.argv)
  File "/usr/local/bin/pwmerge", line 435, in main
    pwm.merge()
  File "/usr/local/bin/pwmerge", line 288, in merge
    self.mark_users(self.spasswd, self.sgroup, self.sur, self.sgr)
  File "/usr/local/bin/pwmerge", line 234, in mark_users
    xpasswd[grm][PW_MARK] = True
KeyError: 'kropfreiterp'
```

The same problem arises with --sgr="NEF" for example:

```
elias@maas:~/tmp$ sudo pwmerge --sur="a^" --sgr="IT" --dur=".*" --dgr=".*" -l etc.server/ etc.boot/ etc.target/
Marked destination users for regexes '.*', '.*':
 root daemon bin sys sync ...
Removed destination users:

Removed destination groups:

Marked source users for regexes 'a^', 'IT':
Traceback (most recent call last):
  File "/usr/local/bin/pwmerge", line 440, in <module>
    main(sys.argv)
  File "/usr/local/bin/pwmerge", line 435, in main
    pwm.merge()
  File "/usr/local/bin/pwmerge", line 288, in merge
    self.mark_users(self.spasswd, self.sgroup, self.sur, self.sgr)
  File "/usr/local/bin/pwmerge", line 234, in mark_users
    xpasswd[grm][PW_MARK] = True
KeyError: 'kropfreiterp'
```

These are the relevant passages in the source and dest files:

```
elias@maas:~/tmp$ sudo grep -R kropfreiterp .
[sudo] password for elias: 
./etc.server/group:adm:x:4:syslog,elias,kropfreiterp,gesselbauerp
./etc.server/group:sudo:x:27:elias,kropfreiterp,gesselbauerp
./etc.server/group:lpadmin:x:118:elias,kropfreiterp,gesselbauerp
./etc.server/group:sambashare:x:128:elias,hanedera,kropfreiterp,gesselbauerp
./etc.server/group:DSL:x:2117:hanedera,holzweberm,weberp,gesselbauerm,kropfreiterp,gesselbauerp
./etc.server/group:IT:x:2001:gesselbauerp,kropfreiterp,elias
./etc.server/group:TL:x:2103:hanedera,neureithert,weinzettlc,bretterbauerc,gesselbauerm,kropfreiterp,paulnsteinerw
./etc.server/group:personal:x:1018:hanedera,neureithert,leithnerb,weisl,paulensteinerw,elias,gesselbauerm,paulnsteinerw,kropfreiterp
./etc.server/group:printall:x:2115:elias,gesselbauerm,hanedera,helmreichp,kropfreiterp,leithnerb,neureithert,paulnsteinerw,weberc,weinzettlc,gesselbauerp
./etc.target/group:adm:x:4:rescue,kropfreiterp,syslog,ubuntu,elias,gesselbauerm
./etc.target/group:sudo:x:27:rescue,kropfreiterp,ubuntu,elias,gesselbauerm
./etc.target/group:lpadmin:x:116:rescue,kropfreiterp,ubuntu,elias,gesselbauerm
./etc.target/group:DSL:x:2117:gesselbauerp,weberp,kropfreiterp,holzweberm,hanedera,gesselbauerm
./etc.target/group:TL:x:2103:weinzettlc,kropfreiterp,neureithert,bretterbauerc,hanedera,gesselbauerm
./etc.target/group:personal:x:1018:kropfreiterp,elias,neureithert,hanedera,paulnsteinerw,leithnerb
./etc.target/shadow:kropfreiterp:OBSCURED:0:99999:7:::
./etc.target/passwd:kropfreiterp:x:1090:2116:Kropfreiter Patrick,,,:/home/kropfreiterp:/bin/bash
./etc.target/gshadow:adm:*::rescue,kropfreiterp,syslog,ubuntu,elias,gesselbauerm
./etc.target/gshadow:sudo:*::rescue,kropfreiterp,ubuntu,elias,gesselbauerm
./etc.target/gshadow:lpadmin:!::rescue,kropfreiterp,ubuntu,elias,gesselbauerm
./etc.target/gshadow:DSL:*::gesselbauerp,weberp,kropfreiterp,holzweberm,hanedera,gesselbauerm
./etc.target/gshadow:TL:*::weinzettlc,kropfreiterp,neureithert,bretterbauerc,hanedera,gesselbauerm
./etc.target/gshadow:personal:*::kropfreiterp,elias,neureithert,hanedera,paulnsteinerw,leithnerb
./etc.boot/group:adm:x:4:syslog,elias,gesselbauerm,kropfreiterp,ubuntu,rescue
./etc.boot/group:sudo:x:27:elias,gesselbauerm,kropfreiterp,ubuntu,rescue
./etc.boot/group:lpadmin:x:116:elias,gesselbauerm,kropfreiterp,ubuntu,rescue
./etc.boot/group:asboe:x:2116:gesselbauerm,kropfreiterp,gesselbauerp,elias,laira
./etc.boot/group:DSL:x:2117:hanedera,holzweberm,weberp,gesselbauerm,kropfreiterp,gesselbauerp
./etc.boot/group:TL:x:2103:hanedera,neureithert,weinzettlc,bretterbauerc,gesselbauerm,kropfreiterp
./etc.boot/group:personal:x:1018:hanedera,neureithert,leithnerb,elias,paulnsteinerw,kropfreiterp
./etc.boot/shadow:kropfreiterp:OBSCURED:16871:0:99999:7:::
./etc.boot/passwd:kropfreiterp:x:1090:2116:Kropfreiter Patrick,,,:/home/kropfreiterp:/bin/bash
```

**Comment by alkisg** [comment]
Try running `pwck` and `grpck` etc on these files to make sure they're valid passwd/group files.

**Comment by alkisg** [comment]
Closing due to lack of feedback.
